[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metamath-logic"
version = "0.0.1"
description = "Logic definitions for Metamath projects"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-2.0-or-later"

authors = [
  { name = "Mingli Yuan" }
]

dependencies = [
    "proof-scaffold",
    "metamath-prelude",
]

[tool.uv.sources]
proof-scaffold = { path = "../proof-scaffold", editable = true }
metamath-prelude = { path = "../metamath-prelude", editable = true }

[tool.setuptools.packages.find]
where = ["src"]
